#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/bin/tools/RunFunctions

wmake combustionModel
wmake solverFoam
runApplication -s 1 solverFoam "PaSR"
wmake PaSR
runApplication -s 2 solverFoam "PaSR" "libPaSR.so"
